echo -n "AWS_ACCESS_KEY_ID:"
read KEY_ID
echo -n "AWS_SECRET_ACCESS_KEY:"
read SECRET_ACCESS_KEY

export AWS_ACCESS_KEY_ID=${KEY_ID}
export AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
export AWS_DEFAULT_REGION="eu-west-1"
bash
